# Generated by Django 4.1.7 on 2023-04-12 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_course_slug_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
