# Generated by Django 4.1.7 on 2023-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emotion_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='name',
        ),
        migrations.AlterField(
            model_name='emotion',
            name='dominant_emotion',
            field=models.CharField(max_length=50),
        ),
    ]
