# Generated by Django 4.1.7 on 2023-04-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_emotion_name_alter_emotion_dominant_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
